{% set name = "globus-compute-sdk" %}
{% set version = "2.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus-compute-sdk-{{ version }}.tar.gz
  sha256: 9d625afa124c43e392997978033604d620cf632e33d24dbaec83b04a67c114ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.31.0,<3
    - globus-sdk >=3.35.0,<4
    - globus-compute-common ==0.4.1
    - websockets ==10.3
    - dill ==0.3.5.1
    - typing-extensions >=4.0
    - packaging >=21.1
    - pika >=1.2
    - tblib ==1.7.0
    - texttable >=1.6.7

test:
  imports:
    - globus_compute_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - WardLT
    - jan-janssen
