{% set name = "globus-compute-sdk" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f5b0f527eb0ba54acf301c6852f96daf7aae2f6a018c4ba6baddaba5530d7dd4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - colorama ==0.4.6
    - psutil <6
    - rich ==13.7.1
    - typing_extensions >=4.0
    - python >={{ python_min }}
    - requests >=2.31.0,<3
    - globus-sdk >=3.51.0,<4
    - globus-compute-common ==0.5.0
    - dill ==0.3.5.1
    - typing-extensions >=4.0
    - packaging >=21.1
    - pika >=1.2
    - tblib ==1.7.0
    - texttable >=1.6.7

test:
  imports:
    - globus_compute_sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/globus/globus-compute
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - rjmello
    - joshbryan-globus
    - khk-globus
    - LeiGlobus
    - chris-janidlo
    - yadudoc
    - ryanchard
    - kylechard
