{% set name = "globus-compute-sdk" %}
{% set version = "2.30.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 603520d647b776a2cf3789e39f3505ca3c4c32485347c71c18e94f1e9ecf05c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - colorama ==0.4.6
    - psutil <6
    - rich ==13.7.1
    - typing_extensions >=4.0
    - python >=3.8
    - requests >=2.31.0,<3
    - globus-sdk >=3.46.0,<4
    - globus-compute-common ==0.4.1
    - websockets ==10.3
    - dill ==0.3.5.1
    - typing-extensions >=4.0
    - packaging >=21.1
    - pika >=1.2
    - tblib ==1.7.0
    - texttable >=1.6.7

test:
  imports:
    - globus_compute_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - rjmello
    - joshbryan-globus
    - khk-globus
    - LeiGlobus
    - chris-janidlo
    - yadudoc
    - ryanchard
    - kylechard
