 {% set name = "globus-compute-sdk" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus-compute-sdk-{{ version }}.tar.gz
  sha256: 750f0d78888a7488e63316dd69a8d67f15a4397af8a3955d6e6f328fd0eb0b76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.20.0
    - globus-sdk >=3.14.0,<4
    - globus-compute-common =0.3.0
    - websockets =10.3
    - dill =0.3.5.1
    - packaging >=21.1
    - pika >=1.2
    - tblib =1.7.0
    - texttable >=1.6.7
    # Set minimum python version to 3.8 to remove typing extensions dependency

test:
  imports:
    - globus_compute_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
    - WardLT
    - jan-janssen
