schema_version: 1

context:
  name: globus-compute-sdk
  version: 4.18.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a2d058f3d1a2c94a58ba9f495918e1167700c159f71851be64a64f845c4ea8cf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - exceptiongroup >=1.2.2
    - colorama >=0.4.6,<1
    - rich >=14,<15
    - python >=${{ python_min }}
    - requests >=2.32,<3
    - globus-sdk >=4.4.0,<5
    - globus-compute-common ==1.0.0
    - dill ==0.3.9
    - packaging >=21.1
    - pika >=1.3
    - tblib >=3
    - texttable >=1.7
tests:
  - python:
      imports:
        - globus_compute_sdk
      pip_check: true
      python_version:
        - ${{ python_min }}
        - '*'

about:
  summary: 'Globus Compute: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/globus/globus-compute

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
    - rjmello
    - khk-globus
    - LeiGlobus
    - chris-janidlo
    - yadudoc
    - ryanchard
    - kylechard
